version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    interval: 'weekly'
      day: 'friday'
    commit-message:
      prefix: 'ghactions'
      include: 'scope'
    labels:
      - infrastructure